spring:
    application:
        name: store
    jwt:
        secret: ${JWT_SECRET}
        accessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
        refreshTokenExpiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
    profiles:
      active: dev
    stripe:
        secretKey: ${STRIPE_SECRET_KEY}
        webhookSecret: ${STRIPE_WEBHOOK_KEY}
