spring:
    datasource:
        url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
        username: root
        password: Test@123
    jpa:
        show-sql: true
    websiteUrl: ${WEBSITE_URL}
